# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    rebase-strategy: "disabled"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 15
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/python" # Location of package manifests
    rebase-strategy: "disabled"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 15
  - package-ecosystem: "github-actions"
    directory: "/"
    rebase-strategy: "disabled"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    open-pull-requests-limit: 15
