#! /usr/bin/env python

import sys
import unittest

#Speedup things...
try:
    import cProfile as profile
except ImportError:
    import profile

def run():
    sys.argv.append('discover')
    unittest.main()

profile.run('run()')
